SystemOrganization addCategory: #'Magma Tools-Buffer Editor'!
SystemOrganization addCategory: #'Magma Tools-Exceptions'!
SystemOrganization addCategory: #'Magma Tools-Health'!
SystemOrganization addCategory: #'Magma Tools-Info'!
SystemOrganization addCategory: #'Magma Tools-Performance'!
SystemOrganization addCategory: #'Magma Tools-Presentation'!
SystemOrganization addCategory: #'Magma Tools-Statistics'!
SystemOrganization addCategory: #'Magma Tools-Stress Tester'!
