SystemOrganization addCategory: #'Ma object serialization-API'!
SystemOrganization addCategory: #'Ma object serialization-Buffers'!
SystemOrganization addCategory: #'Ma object serialization-Info'!
SystemOrganization addCategory: #'Ma object serialization-exceptions'!
SystemOrganization addCategory: #'Ma object serialization-private'!
SystemOrganization addCategory: #'Ma object serialization-support'!
