SystemOrganization addCategory: #'Ma special collections-Collections'!
SystemOrganization addCategory: #'Ma special collections-Dictionarys'!
SystemOrganization addCategory: #'Ma special collections-Dictionarys-Auto'!
SystemOrganization addCategory: #'Ma special collections-Dictionarys-Auto-Tests'!
SystemOrganization addCategory: #'Ma special collections-Exceptions'!
SystemOrganization addCategory: #'Ma special collections-Info'!
SystemOrganization addCategory: #'Ma special collections-Numbers collections'!
SystemOrganization addCategory: #'Ma special collections-Records'!
SystemOrganization addCategory: #'Ma special collections-Sets'!
SystemOrganization addCategory: #'Ma special collections-private'!
