private
legacyClassMap
	^ { 
		(1 -> Metaclass).
		(2 -> Class).
		(3 -> MaClassReference).
		(4 -> MaClassDefinition).
		(5 -> Boolean).
		(6 -> SmallInteger).
		(7 -> Character).
		(8 -> Float).
		(9 -> UndefinedObject).
		(10 -> Array).
		(11 -> ByteSymbol).
		(12 -> ByteString).
		(13 -> ByteArray).
		(14 -> Set).
		(15 -> OrderedCollection).
		(16 -> Dictionary).
		(17 -> True).
		(18 -> False).
		(101 -> ClassDescription).
		(102 -> Behavior).
		(103 -> Object).
		(104 -> ProtoObject).
		(105 -> MaGlobalReference).
		(106 -> MaObject).
		(107 -> Integer).
		(108 -> Number).
		(109 -> Magnitude).
		(110 -> ArrayedCollection).
		(111 -> SequenceableCollection).
		(112 -> Collection).
		(113 -> Symbol).
		(114 -> String)
	 }