SystemOrganization addCategory: #'Ma-Core'!
SystemOrganization addCategory: 'Ma-Core-Abstractions'!
SystemOrganization addCategory: 'Ma-Core-Constants'!
SystemOrganization addCategory: 'Ma-Core-Domain'!
SystemOrganization addCategory: 'Ma-Core-Exceptions'!
SystemOrganization addCategory: 'Ma-Core-Requests'!
SystemOrganization addCategory: 'Ma-Core-SUnit extensions'!
SystemOrganization addCategory: 'Ma-Core-Utilities'!
