SystemOrganization addCategory: #'Magma client-API'!
SystemOrganization addCategory: #'Magma client-Code management'!
SystemOrganization addCategory: #'Magma client-Counter'!
SystemOrganization addCategory: #'Magma client-Domain'!
SystemOrganization addCategory: #'Magma client-Events'!
SystemOrganization addCategory: #'Magma client-Exceptions'!
SystemOrganization addCategory: #'Magma client-Info'!
SystemOrganization addCategory: #'Magma client-Large Collections'!
SystemOrganization addCategory: #'Magma client-MagmaArray'!
SystemOrganization addCategory: #'Magma client-MagmaCollections'!
SystemOrganization addCategory: #'Magma client-Notifications'!
SystemOrganization addCategory: #'Magma client-Preferences'!
SystemOrganization addCategory: #'Magma client-Private'!
SystemOrganization addCategory: #'Magma client-private'!
SystemOrganization addCategory: #'Magma client-private (MagmaCollections)'!
