SystemOrganization addCategory: #'Magma-Server-API'!
SystemOrganization addCategory: #'Magma-Server-Exceptions'!
SystemOrganization addCategory: #'Magma-Server-File'!
SystemOrganization addCategory: #'Magma-Server-Info'!
SystemOrganization addCategory: #'Magma-Server-Preferences'!
SystemOrganization addCategory: #'Magma-Server-Recovery'!
SystemOrganization addCategory: #'Magma-Server-Utilities'!
SystemOrganization addCategory: #'Magma-Server-private'!
