as yet unclassified
changesText

	^'
1.0gamma8
	- Now has 1-click kickoff of the test cases by evaluating "MagmaTestCase kickoff".  Now requires OSProcess to accomplish this.
	- Tremendous increase in stringency of Morph test by storing and retrieving a MauiCollectionMorph instead of a single RectangleMorph.
	- Added tests involving MagmaFixtureFactory to generate all possible objects Magma supports (requires DictionaryEquivalencePerformanceBoost).

1.0gamma7
	- Extra stringent tests for MaHashIndex and MaHashIndexRecord ensure ultra-reliable support for MagmaCollections.'