SystemOrganization addCategory: #'Magma server-API'!
SystemOrganization addCategory: #'Magma server-Exceptions'!
SystemOrganization addCategory: #'Magma server-File'!
SystemOrganization addCategory: #'Magma server-Info'!
SystemOrganization addCategory: #'Magma server-Preferences'!
SystemOrganization addCategory: #'Magma server-Recovery'!
SystemOrganization addCategory: #'Magma server-Utilities'!
SystemOrganization addCategory: #'Magma server-private'!
