SystemOrganization addCategory: #'Magma-Client'!
SystemOrganization addCategory: 'Magma-Client-API'!
SystemOrganization addCategory: 'Magma-Client-Code management'!
SystemOrganization addCategory: 'Magma-Client-Counting'!
SystemOrganization addCategory: 'Magma-Client-Data Repair'!
SystemOrganization addCategory: 'Magma-Client-Domain'!
SystemOrganization addCategory: 'Magma-Client-Events'!
SystemOrganization addCategory: 'Magma-Client-Exceptions'!
SystemOrganization addCategory: 'Magma-Client-Info'!
SystemOrganization addCategory: 'Magma-Client-MagmaArray'!
SystemOrganization addCategory: 'Magma-Client-MagmaCollections'!
SystemOrganization addCategory: 'Magma-Client-Notifications'!
SystemOrganization addCategory: 'Magma-Client-private'!
SystemOrganization addCategory: 'Magma-Client-private (MagmaCollections)'!
