SystemOrganization addCategory: #'Ma-Serializer-Core'!
SystemOrganization addCategory: 'Ma-Serializer-Core-API'!
SystemOrganization addCategory: 'Ma-Serializer-Core-Buffers'!
SystemOrganization addCategory: 'Ma-Serializer-Core-Exceptions'!
SystemOrganization addCategory: 'Ma-Serializer-Core-Info'!
SystemOrganization addCategory: 'Ma-Serializer-Core-Proxy'!
SystemOrganization addCategory: 'Ma-Serializer-Core-private'!
