SystemOrganization addCategory: #'Ma-Collections-Canonicalization'!
SystemOrganization addCategory: #'Ma-Collections-Collections'!
SystemOrganization addCategory: #'Ma-Collections-Dictionarys'!
SystemOrganization addCategory: #'Ma-Collections-Dictionarys-Auto'!
SystemOrganization addCategory: #'Ma-Collections-Dictionarys-Auto-Tests'!
SystemOrganization addCategory: #'Ma-Collections-Exceptions'!
SystemOrganization addCategory: #'Ma-Collections-Info'!
SystemOrganization addCategory: #'Ma-Collections-Numbers collections'!
SystemOrganization addCategory: #'Ma-Collections-Records'!
SystemOrganization addCategory: #'Ma-Collections-Sets'!
SystemOrganization addCategory: #'Ma-Collections-Tests'!
SystemOrganization addCategory: #'Ma-Collections-Tree'!
SystemOrganization addCategory: #'Ma-Collections-private'!
SystemOrganization addCategory: #'Ma-Collections-BTree'!
