icons
newDocumentIcon
	^ self 
		iconNamed: #newDocumentIcon
		ifAbsentPutFromString: 'iVBORw0KGgoAAAANSUhEUgAAABoAAAAWCAYAAADeiIy1AAABf0lEQVR4XmMAAauANGWbgAwH
amJ731RToNGMDDDgHJ5f19Gz+N/iWev/928/9797x5n/k7edJwt37jz9f+K2c/87dpz6XzF9
/X87/8wTcIuyWue9ee3k+X/vvf//m85f/p92ZN//7U///t/17D9JeMX9j/9TDu/5337xBpie
e+vF//jyCf81TN18gdawMriGF35Y1rvw/76euf+nn7j9v/f41f+LTj4iGS84+fB/5/HL/2ed
vAumOzcc/+8YnPNfXtO0FmiRDYOtX/qHzLKu/+u3Hfi/bc8xquCNOw79z6/p+w80G2aRL4NT
cPaHj5+//P/+fy9V8c+fv/77xZYgLApLrf5EbUtgOK+qd+RbNPItGvkWkYn/f2eAY5pZhGwJ
DIMt8o4u+vj371+aWQK3zMYv7c685Zv/f//xk+oWTZkyBWGRlXdClo1v2g9QSUspRrcExSIg
4OLk5osSkVTIoAbGGUfQet0diIOohdEsAYmZwWp0ZiAWAWJRGmBBkAUAx4Ad+Vy9w0QAAAAA
SUVORK5CYII='