SystemOrganization addCategory: #'Magma-Tools-Buffer Editor'!
SystemOrganization addCategory: #'Magma-Tools-Data Repair'!
SystemOrganization addCategory: #'Magma-Tools-Exceptions'!
SystemOrganization addCategory: #'Magma-Tools-Health'!
SystemOrganization addCategory: #'Magma-Tools-Info'!
SystemOrganization addCategory: #'Magma-Tools-Performance'!
SystemOrganization addCategory: #'Magma-Tools-Stress Tester'!
SystemOrganization addCategory: #'Magma-Tools-Upgrade'!
